### ISSUE TITLE
Texture issues on faces

### ISSUE THREAD

**Issue by ekianjo** [virtual-programming/bioshockinfinite-linux#4] opened 2015-04-24 04:43 UTC
Not always easy to reproduce, but in several cases, the textures on the character's faces look fine from afar, but when you come too close to them they suddenly become black. Nvidia GTX460, OpenSuse 13.1, and the driver was 346.59. 

Sometimes restarting the game would solve the issue - so I'm not entirely sure where it comes from and how to reproduce it in the first place - but it happened several times throughout the game (up until the end), while not always.

**Comment by vpltd-peterm** [comment] 2015-04-24 09:16
OK, if you manage to find a way to reproduce it, and get screenshots, please let us know

**Comment by vpltd-peterm** [comment] 2015-06-10 20:50
AS noone else has reported this, and noone seems to be able to reproduce it, im closing this.

**Closed by vpltd-peterm** 2015-06-10 20:50 UTC
Labels: Feedback Requested
