### ISSUE TITLE
Textures missing on AMD Terascale GPUs

### ISSUE THREAD

**Issue by bjarkig** [virtual-programming/bioshockinfinite-linux#10] opened 2015-04-24 15:50 UTC
The issue is basically that no dynamic/moving objects have textures, whether in the intro or in-game. Runs fine, it's the only noticeable problem.

I'm running on an AMD Radeon HD 6800, fglrx 14.20
8 GB RAM
Intel Quad Core 2 Ghz

![2015-03-22_00001](https://cloud.githubusercontent.com/assets/6422973/7322581/7120fb5e-ea98-11e4-9373-c9e20ffbf2ae.jpg)

![2015-03-22_00002](https://cloud.githubusercontent.com/assets/6422973/7322583/731ea870-ea98-11e4-93d9-02f649e8479d.jpg)

**Comment by vpltd-peterm** [comment] 2015-04-24 15:58
As stated in the product requirements, we are currently only supporting AMD GCN based hardware, that is the Radeon 77xx and newer.

This is because of a bug in AMD Catalyst drivers, which means GL_EXT_texture_compression_rgtc does not correctly function on Terascale hardware. This produces the effect seen here.

Unfortunately we cannot work around this, so it is up to AMD to fix it.

**Comment by xpris** [comment] 2015-05-10 17:11
@vpltd-peterm 
I guess you have direct contact to AMD. So maybe do you know some new news?
Is AMD working on fixing this issue or not?

**Comment by vpltd-peterm** [comment] 2015-05-29 14:08
We have reported it, but they have been quiet so far.

**Comment by Recydywa** [comment] 2015-07-12 10:46
One user reported that the newest drivers 15.7 resolved the issue for him on Radeon HD 5850. So far no one else confirmed it.

http://steamcommunity.com/app/8870/discussions/0/537402115078131777/

**Comment by xpris** [comment] 2015-07-12 12:34
Cool, If this is true I instant buy BI. I have the same GPU like user with this topic, so I hope it it true.
VP can you confirm?

**Comment by vpltd-peterm** [comment] 2015-07-12 16:57
It does seem as if the AMD Catalyst 15.7 driver resolves this problem.. so far I have only tested on a Radeon 6870, and we'll advise 2K of it so they can do further testing if it seems to be true.

I have noticed one caveat - if you attempt to force Anti-Aliasing through the AMD Catalyst Control Panel, texture corruption will occur in game. However, if you do not do this the game seems to run fine.

**Comment by vpltd-peterm** [comment] 2015-07-12 16:58
If anyone else with a Terascale card can confirm this, please post here, listing what card you have.

**Comment by Holzhaus** [comment] 2015-07-12 20:40
I had this problem with Catalyst 15.5, but I seems to work fine in 15.7. Didn't have time to test anti-aliasing just yet though.

# Some screenshots
![Screenshow on low settings 1](http://i.imgur.com/wEnc8BO.jpg)
People were missing textures, looks fine now.

![Screenshow on low settings 1](http://i.imgur.com/Aubwidt.jpg)

The façade to the right was missing textures, now it's working.

![Screenshow on low settings 1](http://i.imgur.com/suzJW0F.jpg)

Also, the guy in the chair had no textures with Catalyst 15.5, now it works.

![Screenshot on Ultra settings](http://i.imgur.com/2rbzvEF.jpg)
A screenshot on ultra settings (more like slide show on my Hardware though)

# System Information
```
OS Version:
  Linux Distribution: Arch Linux
  Kernel Version:     4.0.7-2-ARCH #1 SMP PREEMPT Tue Jun 30 07:50:21 UTC 2015

Hardware Info:
  Machine Type:       Hewlett-Packard HP ProBook 6465b A0001D02
  CPU Type:           AuthenticAMD x86_64
  CPU Info:           AMD A6-3410MX APU with Radeon(tm) HD Graphics
  CPU Speed:          1600 MHz
  CPU Physical Cores: 4
  CPU Logical Cores:  4
  Physical Memory:    7629276 KiB
  Virtual Memory:     0 KiB

Direct3D -> OpenGL context information:
  renderer: AMD Radeon HD 6520G
  vendor: ATI Technologies Inc.
  version: 4.1.13397 Core Profile Context 15.20.1013
  GLSL version: 4.40
  max color attachment and draw buffers: 8
  max amount of samplers: 108
  max vertex shader uniform blocks: 14
  max geometry shader uniform blocks: 14
  max fragment shader uniform blocks: 14
  max hull shader uniform blocks: 14
  max domain shader uniform blocks: 14
  max compute shader uniform blocks: 14
  max viewports: 16
  max uniform buffer bindings: 90
  max pixel shader UAVs: 8
  max compute shader UAVs: 8
  max UAVs: 8
  uniform buffer offset alignment: 256
  buffer_storage support: yes
  compressed_texture_pixel_storage support: yes
```

**Comment by not83** [comment] 2015-07-13 10:00
@vpltd-peterm When virtual programming software gets updated (bux fixes, future game support) is that same code base then updated on existing games? When new code gets made for Bioshock does Witcher 2 then get updated?

**Comment by vpltd-peterm** [comment] 2015-07-13 10:51
Not automatically, if we have reason to believe that there may be some bug fix or performance improvement, then we would do it.. but we dont update all "just because".

**Comment by not83** [comment] 2015-07-15 01:11
@vpltd-peterm Ahh fair enough :)

**Comment by eydee** [comment] 2015-07-19 16:26
Confirmed to be working on 15.7. Finally!

**Comment by Holzhaus** [comment] 2015-07-25 23:09
@vpltd-peterm I think you can safely close this now.

**Closed** 2015-08-02 11:49 UTC
Labels: Feedback Requested, Known Issue
