### ISSUE TITLE
Official microsoft Xbox 360 wireless controller

### ISSUE THREAD

**Issue by Gabullito** [virtual-programming/bioshockinfinite-linux#26] opened 2015-07-21 17:41 UTC
Hello,
I have an issue with my gamepad buttons ( LT RT LB RB ) not working in game
Cordialy
OS: SteamOS 1.0
Gamepad : Official microsoft Xbox 360 wireless controller

**Comment by dubigrasu** [comment] 2015-07-22 22:20
Most likely the same issue as https://github.com/virtual-programming/bioshockinfinite-linux/issues/23

**Comment by vpltd-peterm** [comment] 2015-09-05 22:40
Closing as duplicate of #23

**Closed by vpltd-peterm** 2015-09-05 22:40 UTC
