### ISSUE TITLE
Black screen after AMD Gaming Evolved video, before copyright page, on 6-core HT processor

### ISSUE THREAD

**Issue by directhex** [virtual-programming/bioshockinfinite-linux#9] opened 2015-04-24 15:40 UTC
eon.txt log: https://gist.github.com/directhex/41c23705ba6d56f7d96a

**Comment by vpltd-peterm** [comment] 2015-04-24 15:56
The game uses OpenAL Soft, so you could try creating an .alsoftrc which forces the use of the ALSA driver to check this

**Comment by directhex** [comment] 2015-04-25 20:26
```
$ cat .alsoftrc 
[general]
drivers = alsa
[alsa]
device = sysdefault
$ aplay -L | grep -A2 sysdef
sysdefault:CARD=PCH
    HDA Intel PCH, ALC1150 Analog
    Default Audio Device
```

That look about right? Because it has no effect.

**Comment by vpltd-peterm** [comment] 2015-04-25 21:34
Could you attach GDB to the process when you get a hang and post the output of "thread apply all bt full" ?

**Comment by directhex** [comment] 2015-04-26 20:48
https://gist.github.com/directhex/564c76e65ca00dc26692

What a lot of threads

**Comment by directhex** [comment] 2015-04-26 22:30
It's a threading issue.

I forced single-threaded execution via "taskset -c 11 %command%" and the game loaded up fine.

My processor, an i7-5820k, has 6 cores w/ hyperthreading.

Removing __GL_THREADED_OPTIMIZATIONS=1 from the launcher script had no effect, so I don't think the threading issue relates to NVIDIA's code.

**Comment by vpltd-peterm** [comment] 2015-04-28 10:09
related to #1

**Comment by vpltd-peterm** [comment] 2015-06-16 18:22
Closing as likely duplicate of #1

**Closed by vpltd-peterm** 2015-06-16 18:22 UTC
