### ISSUE TITLE
Xbox One controller trigger buttons dont work

### ISSUE THREAD

**Issue by creeperlwd** [virtual-programming/bioshockinfinite-linux#33] opened 2015-09-03 07:44 UTC
Arch linux 4.1.6-1
Official xbox one controller
I tried other gamepad profiles that also didnt work

**Comment by vpltd-peterm** [comment] 2015-09-05 22:39
We may have found the cause of this in another title (Dirt Showdown). We are planning to release updates to affected titles.

**Comment by vpltd-peterm** [comment] 2015-09-05 22:40
Closing as duplicate of #23

**Closed by vpltd-peterm** 2015-09-05 22:40 UTC
