### ISSUE TITLE
Weird color artifacts?

### ISSUE THREAD

**Issue by CommanderAlchemy** [virtual-programming/bioshockinfinite-linux#24] opened 2015-07-12 02:42 UTC
I have noticed this on few places in the game, first in the beginning before the fare where you go around and play games (shoot the targets) and as in the picture it happens when the brightness goes upp and down on the picture. Only shows up when it's at the brightest.

![screenshot1](https://cloud.githubusercontent.com/assets/3089330/8636116/69f63bc8-2850-11e5-8c9c-081c04327d88.png)

#### Video of the occurrence
[![ScreenShot](http://img.youtube.com/vi/5JHs_khn9iI/0.jpg)](http://i.imgur.com/ZuHljse.gifv)

![screenshot1](https://cloud.githubusercontent.com/assets/3089330/8636233/4d2d95e4-2856-11e5-86c4-2a522e24ba63.png)

![screenshot1](https://cloud.githubusercontent.com/assets/3089330/8636277/5d63f0fe-2859-11e5-9ae1-c51dad782fd8.png)

### [Steamsysteminfo](https://gist.github.com/CommanderAlchemy/83c70f2deffb678192c3)

**Comment by vpltd-peterm** [comment] 2015-07-12 10:53
Duplicate of #8

**Closed by vpltd-peterm** 2015-07-12 10:53 UTC
